const selectors = require('../supporting/selectors')
const data = require('../supporting/data')

module.exports = {
    beforeEach: browser => {
        browser.url('http://localhost:3000')

    },
    after: browser => {
        browser.end()
    },
    // "WQ27": browser => {
    //     browser
    //         .click(selectors.buttons.menuIcon)
    //         .waitForElementVisible(selectors.buttons.enterOption, 4000)
    //         .click(selectors.buttons.enterOption)
    //         .pause(10000)
    //         .waitForElementVisible(selectors.fields.hdrInput, 4000)
    //         .setValue(selectors.fields.hdrInput, data.WQ27.hdr)
    //         .setValue(selectors.fields.mkeInput, data.WQ27.mke)
    //         .setValue(selectors.fields.oriInput, data.WQ27.ori)
    //         .setValue(selectors.fields.namInput, data.WQ27.nam)
    //         .click(selectors.fields.sexInput)
    // },

    "WQ29": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 10000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.fields.hdrInput, 10000)
            .setValue(selectors.fields.hdrInput, data.WQ29.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ29.mke)
            .setValue(selectors.fields.oriInput, data.WQ29.oai)
            .setValue(selectors.fields.namInput, data.WQ29.nam)
            // .setValue(selectors.fields.sexInput, data.WQ29.sex)
            .click(selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.dropDownBoxes.raceField.americanIndian)
            .setValue(selectors.fields.hgtInput, data.WQ29.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ29.wgt)
            .setValue(selectors.fields.haiInput, data.WQ29.hai)
            .setValue(selectors.fields.offInput, data.WQ29.off)
            .setValue(selectors.fields.dowInput, data.WQ29.dow)
            .setValue(selectors.fields.olnInput, data.WQ29.oln)
            .setValue(selectors.fields.olsInput, data.WQ29.ols)
            .setValue(selectors.fields.oldInput, data.WQ29.old)
            .setValue(selectors.fields.licInput, data.WQ29.lic)
            .setValue(selectors.fields.lisInput, data.WQ29.lis)
            .setValue(selectors.fields.lidInput, data.WQ29.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.contain("Johnson1234567890$#.Ab*&.J8765kI90.MRS Bingo Big Daddy $$$!!!!!!!.U.I.190.999.blackerish.123456789Zsw@#$.2017-02-07.aBcdef!23$567896Hnj*.TX.2002-01-31.12345Hui.HI.1941-04-06")

    },
    "WQ253": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.modifyOption, 10000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.widInput, 10000)
            .click(selectors.fields.widInput)
            .setValue(selectors.fields.widInput, data.WQ253.wid)
            .setValue(selectors.fields.hdrInput, data.WQ253.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ253.mke)
            .setValue(selectors.fields.oriInput, data.WQ253.oai)
            .setValue(selectors.fields.namInput, data.WQ253.nam)
            .click(selectors.dropDownBoxes.sexField.female)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ253.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ253.wgt)
            .setValue(selectors.fields.haiInput, data.WQ253.hai)
            .setValue(selectors.fields.offInput, data.WQ253.off)
            .setValue(selectors.fields.dowInput, data.WQ253.dow)
            .setValue(selectors.fields.olnInput, data.WQ253.oln)
            .setValue(selectors.fields.olsInput, data.WQ253.ols)
            .setValue(selectors.fields.oldInput, data.WQ253.old)
            .setValue(selectors.fields.licInput, data.WQ253.lic)
            .setValue(selectors.fields.lisInput, data.WQ253.lis)
            .setValue(selectors.fields.lidInput, data.WQ253.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.contain("1278569032.^yh8i(kmtred$3234Ft.hu*!.456iOKuj0.My name is what I want it to b.F.W.098.999.chocolatey.ju6^89iesryy3!s.1981-10-19.JKio98765%7)(jnye#)t.CA.2005-04-16.Mai7629j.MN.1978-07-19")

    },
    //Will not pass at this time due to but WQ2-68
    // "WQ259": browser => {
    //     browser
    //         .click(selectors.buttons.menuIcon)
    //         .waitForElementVisible(selectors.buttons.cancelOption, 10000)
    //         .click(selectors.buttons.cancelOption)
    //         .waitForElementVisible(selectors.fields.widInput, 10000)
    //         .setValue(selectors.fields.widInput, data.WQ259.wid)
    //         .setValue(selectors.fields.resInput, data.WQ259.res)
    //         .setValue(selectors.fields.datInput, data.WQ259.date)
    //         .click(selectors.buttons.saveBtn)
    //     browser.expect.element(selectors.paragrahHeadings.queryBody)
    // },
    "WQ234": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 10000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.fields.hdrInput, 10000)
            .setValue(selectors.fields.hdrInput, data.WQ234.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ234.mke)
            .setValue(selectors.fields.oriInput, data.WQ234.ori)
            .setValue(selectors.fields.namInput, data.WQ234.nam)
            .click(selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.dropDownBoxes.raceField.americanIndian)
            .setValue(selectors.fields.hgtInput, data.WQ234.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ234.wgt)
            .setValue(selectors.fields.haiInput, data.WQ234.hai)
            .setValue(selectors.fields.offInput, data.WQ234.off)
            .setValue(selectors.fields.dowInput, data.WQ234.dow)
            .setValue(selectors.fields.olnInput, data.WQ234.oln)
            .setValue(selectors.fields.olsInput, data.WQ234.ols)
            .setValue(selectors.fields.oldInput, data.WQ234.old)
            .setValue(selectors.fields.licInput, data.WQ234.lic)
            .setValue(selectors.fields.lisInput, data.WQ234.lis)
            .setValue(selectors.fields.lidInput, data.WQ234.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "MKE" field can only include characters from the English Alphabet or special characters.')
        // browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Originating Agency Identifier" field can only include characters from the English Alphabet or numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field needs to have a value greater than 0.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field has one or more periods, which are unacceptable in any field.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Hair" field can only include characters from the English Alphabet or special characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "DL State" field can only include a valid State/Territory abbreviation.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License Plate" field can only include characters from the English Alphabet or numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License State" field can only include a valid State/Territory abbreviation.')
    },
    "WQ257": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.modifyOption, 10000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.widInput, 10000)
            .click(selectors.fields.widInput)
            .setValue(selectors.fields.widInput, data.WQ257.wid)
            .setValue(selectors.fields.hdrInput, data.WQ257.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ257.mke)
            .setValue(selectors.fields.oriInput, data.WQ257.oai)
            .setValue(selectors.fields.namInput, data.WQ257.nam)
            .click(selectors.dropDownBoxes.sexField.female)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ257.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ257.wgt)
            .setValue(selectors.fields.haiInput, data.WQ257.hai)
            .setValue(selectors.fields.offInput, data.WQ257.off)
            .setValue(selectors.fields.dowInput, data.WQ257.dow)
            .setValue(selectors.fields.olnInput, data.WQ257.oln)
            .setValue(selectors.fields.olsInput, data.WQ257.ols)
            .setValue(selectors.fields.oldInput, data.WQ257.old)
            .setValue(selectors.fields.licInput, data.WQ257.lic)
            .setValue(selectors.fields.lisInput, data.WQ257.lis)
            .setValue(selectors.fields.lidInput, data.WQ257.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "MKE" field can only include characters from the English Alphabet or special characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Originating Agency Identifier" field can only include characters from the English Alphabet or numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field needs to have a value greater than 0.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field needs to have a value greater than 0.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Hair" field can only include characters from the English Alphabet or special characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "DL State" field can only include a valid State/Territory abbreviation.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License Plate" field can only include characters from the English Alphabet or numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License State" field can only include a valid State/Territory abbreviation.')
    },

    "WQ261": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.cancelOption, 10000)
            .click(selectors.buttons.cancelOption)
            .waitForElementVisible(selectors.fields.widInput, 10000)
            .click(selectors.fields.widInput)
            .setValue(selectors.fields.widInput, data.WQ261.wid)
            .setValue(selectors.fields.resInput, data.WQ261.res)
            .setValue(selectors.fields.datInput, data.WQ261.date)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field can only include numeric characters.')
    },
    "WQ227": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 10000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.fields.hdrInput, 10000)
            .setValue(selectors.fields.hdrInput, data.WQ227.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ227.mke)
            .setValue(selectors.fields.oriInput, data.WQ227.oai)
            .setValue(selectors.fields.namInput, data.WQ227.nam)
            // .setValue(selectors.fields.sexInput, data.WQ227.sex)
            .click(selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.dropDownBoxes.raceField.americanIndian)
            .setValue(selectors.fields.hgtInput, data.WQ227.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ227.wgt)
            .setValue(selectors.fields.haiInput, data.WQ227.hai)
            .setValue(selectors.fields.offInput, data.WQ227.off)
            .setValue(selectors.fields.dowInput, data.WQ227.dow)
            .setValue(selectors.fields.olnInput, data.WQ227.oln)
            .setValue(selectors.fields.olsInput, data.WQ227.ols)
            .setValue(selectors.fields.oldInput, data.WQ227.old)
            .setValue(selectors.fields.licInput, data.WQ227.lic)
            .setValue(selectors.fields.lisInput, data.WQ227.lis)
            .setValue(selectors.fields.lidInput, data.WQ227.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Header" field should be between 9 and 19 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "MKE" field should be between 2 and 4 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Originating Agency Identifier" field should be 9 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Name" field should be between 3 and 30 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field should be 3 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field should be between 1 and 3 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Hair" field should be between 3 and 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Offense" field should be between 5 and 15 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Drivers License" field should be between 1 and 20 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "DL State" field should be 2 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License Plate" field should be between 5 and 8 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License State" field should be 2 characters long.')
    },
    "WQ250": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.modifyOption, 10000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.widInput, 10000)
            .setValue(selectors.fields.widInput, data.WQ250.wid)
            .setValue(selectors.fields.hdrInput, data.WQ250.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ250.mke)
            .setValue(selectors.fields.oriInput, data.WQ250.oai)
            .setValue(selectors.fields.namInput, data.WQ250.nam)
            .click(selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.dropDownBoxes.raceField.americanIndian)
            .setValue(selectors.fields.hgtInput, data.WQ250.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ250.wgt)
            .setValue(selectors.fields.haiInput, data.WQ250.hai)
            .setValue(selectors.fields.offInput, data.WQ250.off)
            .setValue(selectors.fields.dowInput, data.WQ250.dow)
            .setValue(selectors.fields.olnInput, data.WQ250.oln)
            .setValue(selectors.fields.olsInput, data.WQ250.ols)
            .setValue(selectors.fields.oldInput, data.WQ250.old)
            .setValue(selectors.fields.licInput, data.WQ250.lic)
            .setValue(selectors.fields.lisInput, data.WQ250.lis)
            .setValue(selectors.fields.lidInput, data.WQ250.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field should be 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Header" field should be between 9 and 19 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "MKE" field should be between 2 and 4 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Originating Agency Identifier" field should be 9 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Name" field should be between 3 and 30 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field should be 3 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field should be between 1 and 3 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Hair" field should be between 3 and 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Offense" field should be between 5 and 15 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Drivers License" field should be between 1 and 20 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "DL State" field should be 2 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License Plate" field should be between 5 and 8 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "License State" field should be 2 characters long.')
    },
    "WQ260": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.cancelOption, 10000)
            .click(selectors.buttons.cancelOption)
            .waitForElementVisible(selectors.fields.widInput, 10000)
            .click(selectors.fields.widInput)
            .setValue(selectors.fields.widInput, data.WQ260.wid)
            .setValue(selectors.fields.resInput, data.WQ260.res)
            .setValue(selectors.fields.datInput, data.WQ260.date)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field should be 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Reason for Cancellation" field should be between 10 and 150 characters long.')
    },

    "WQ26": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.fields.hdrInput, 2000)
            .setValue(selectors.fields.hdrInput, data.WQ26.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ26.mke)
            .setValue(selectors.fields.oriInput, data.WQ26.ori)
            .setValue(selectors.fields.namInput, data.WQ26.nam)
            .click(selectors.dropDownBoxes.sexField.male)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ26.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ26.wgt)
            .setValue(selectors.fields.haiInput, data.WQ26.hai)
            .setValue(selectors.fields.offInput, data.WQ26.off)
            .setValue(selectors.fields.dowInput, data.WQ26.dow)
            .setValue(selectors.fields.olnInput, data.WQ26.oln)
            .setValue(selectors.fields.olsInput, data.WQ26.ols)
            .setValue(selectors.fields.oldInput, data.WQ26.old)
            .setValue(selectors.fields.licInput, data.WQ26.lic)
            .setValue(selectors.fields.lisInput, data.WQ26.lis)
            .setValue(selectors.fields.lidInput, data.WQ26.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.validHeader).text.to.equal(data.WQ26.header)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.equal(data.WQ26.errorList)
        browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.equal(data.WQ26.queryTitle)
        browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.equal(data.WQ26.assembledQueryEnter)
    },
    //The zero at the end of the test name is to symbolize the same test but for modify wanted
    "WQ260": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.hdrInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ26.wid)
            .setValue(selectors.fields.hdrInput, data.WQ26.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ26.mke)
            .setValue(selectors.fields.oriInput, data.WQ26.ori)
            .setValue(selectors.fields.namInput, data.WQ26.nam)
            .click(selectors.dropDownBoxes.sexField.male)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ26.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ26.wgt)
            .setValue(selectors.fields.haiInput, data.WQ26.hai)
            .setValue(selectors.fields.offInput, data.WQ26.off)
            .setValue(selectors.fields.dowInput, data.WQ26.dow)
            .setValue(selectors.fields.olnInput, data.WQ26.oln)
            .setValue(selectors.fields.olsInput, data.WQ26.ols)
            .setValue(selectors.fields.oldInput, data.WQ26.old)
            .setValue(selectors.fields.licInput, data.WQ26.lic)
            .setValue(selectors.fields.lisInput, data.WQ26.lis)
            .setValue(selectors.fields.lidInput, data.WQ26.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.validHeader).text.to.equal(data.WQ26.header)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.equal(data.WQ26.errorList)
        browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.equal(data.WQ26.queryTitle)
        browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.equal(data.WQ26.assembledQueryModify)
    },
    //Commented out the following test since there is a bug: WQ2-68
    // "WQ23": browser => {
    //     browser
    //         .click(selectors.buttons.menuIcon)
    //         .waitForElementVisible(selectors.buttons.enterOption, 2000)
    //         .click(selectors.buttons.enterOption)
    //         .waitForElementVisible(selectors.fields.hdrInput, 2000)
    //         .setValue(selectors.fields.hdrInput, data.WQ23.hdr)
    //         .setValue(selectors.fields.mkeInput, data.WQ23.mke)
    //         .setValue(selectors.fields.oriInput, data.WQ23.ori)
    //         .setValue(selectors.fields.namInput, data.WQ23.nam)
    //         .click(selectors.dropDownBoxes.sexField.male)
    //         .click(selectors.dropDownBoxes.raceField.white)
    //         .setValue(selectors.fields.hgtInput, data.WQ23.hgt)
    //         .setValue(selectors.fields.wgtInput, data.WQ23.wgt)
    //         .setValue(selectors.fields.haiInput, data.WQ23.hai)
    //         .setValue(selectors.fields.offInput, data.WQ23.off)
    //         .setValue(selectors.fields.dowInput, data.WQ23.dow)
    //         .setValue(selectors.fields.olnInput, data.WQ23.oln)
    //         .setValue(selectors.fields.olsInput, data.WQ23.ols)
    //         .setValue(selectors.fields.oldInput, data.WQ23.old)
    //         .setValue(selectors.fields.licInput, data.WQ23.lic)
    //         .setValue(selectors.fields.lisInput, data.WQ23.lis)
    //         .setValue(selectors.fields.lidInput, data.WQ23.lid)
    //         .click(selectors.buttons.saveBtn)
    //     browser.expect.element(selectors.paragrahHeadings.validHeader).text.to.equal(data.WQ23.header)
    //     browser.expect.element(selectors.paragrahHeadings.errorList).text.to.equal(data.WQ23.errorList)
    //     browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.equal(data.WQ23.queryTitle)
    //     browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.equal(data.WQ23.assembledQueryEnter)
    // },
    "WQ230": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.hdrInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ23.wid)
            .setValue(selectors.fields.hdrInput, data.WQ23.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ23.mke)
            .setValue(selectors.fields.oriInput, data.WQ23.ori)
            .setValue(selectors.fields.namInput, data.WQ23.nam)
            .click(selectors.dropDownBoxes.sexField.male)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ23.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ23.wgt)
            .setValue(selectors.fields.haiInput, data.WQ23.hai)
            .setValue(selectors.fields.offInput, data.WQ23.off)
            .setValue(selectors.fields.dowInput, data.WQ23.dow)
            .setValue(selectors.fields.olnInput, data.WQ23.oln)
            .setValue(selectors.fields.olsInput, data.WQ23.ols)
            .setValue(selectors.fields.oldInput, data.WQ23.old)
            .setValue(selectors.fields.licInput, data.WQ23.lic)
            .setValue(selectors.fields.lisInput, data.WQ23.lis)
            .setValue(selectors.fields.lidInput, data.WQ23.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.validHeader).text.to.equal(data.WQ23.header)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.equal(data.WQ23.errorList)
        browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.equal(data.WQ23.queryTitle)
        browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.equal(data.WQ23.assembledQueryModify)
    },
    //This test is to submit valid data. I commented out the test since it results in an error (WQ2)
    // "WQ216": browser => {
    //     browser
    //     .click(selectors.buttons.menuIcon)
    //     .waitForElementVisible(selectors.buttons.enterOption, 2000)
    //     .click(selectors.buttons.cancelOption)
    //     .waitForElementVisible(selectors.fields.widInput, 2000)
    //     .setValue(selectors.fields.widInput, data.WQ216.wid)
    //     .setValue(selectors.fields.resInput, data.WQ216.RFC)
    //     .setValue(selectors.fields.datInput, data.WQ216.DOC)
    //     .click(selectors.buttons.saveBtn)
    // browser.expect.element(selectors.paragrahHeadings.validHeader).text.to.equal(data.WQ216.header)
    // browser.expect.element(selectors.paragrahHeadings.errorList).text.to.equal(data.WQ216.errorList)
    // browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.equal(data.WQ216.queryTitle)
    // browser.expect.element(selectors.paragrahHeadings.queryBody).text.to.equal(data.WQ216.assembledQuery)
    // },

    //this test has a zero in the name since we are clicking clear
    "WQ218": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.cancelOption)
            .waitForElementVisible(selectors.fields.widInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ218.wid)
            .setValue(selectors.fields.resInput, data.WQ218.RFC)
            .setValue(selectors.fields.datInput, data.WQ218.DOC)
            .click(selectors.buttons.clearBtn)
        browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.contain('Submit query for validation.')
    },
    "WQ217": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.cancelOption)
            .waitForElementVisible(selectors.fields.widInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ217.wid)
            .setValue(selectors.fields.resInput, data.WQ217.RFC)
            .setValue(selectors.fields.datInput, data.WQ217.DOC)
            .click(selectors.buttons.clearBtn)
        browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.contain('Submit query for validation.')
    },
    "WQ28": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.fields.hdrInput, 2000)
            .setValue(selectors.fields.hdrInput, data.WQ28.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ28.mke)
            .setValue(selectors.fields.oriInput, data.WQ28.ori)
            .setValue(selectors.fields.namInput, data.WQ28.nam)
            .click(selectors.dropDownBoxes.sexField.male)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ28.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ28.wgt)
            .setValue(selectors.fields.haiInput, data.WQ28.hai)
            .setValue(selectors.fields.offInput, data.WQ28.off)
            .setValue(selectors.fields.dowInput, data.WQ28.dow)
            .setValue(selectors.fields.olnInput, data.WQ28.oln)
            .setValue(selectors.fields.olsInput, data.WQ28.ols)
            .setValue(selectors.fields.oldInput, data.WQ28.old)
            .setValue(selectors.fields.licInput, data.WQ28.lic)
            .setValue(selectors.fields.lisInput, data.WQ28.lis)
            .setValue(selectors.fields.lidInput, data.WQ28.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Sex" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Race / Ethnicity" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field needs to have a value greater than 0.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field needs to have a value greater than 0.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Hair" field can only include characters from the English Alphabet or special characters.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Offense" field has one or more periods, which are unacceptable in any field.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Date of Warrant/Violation" field must be included.')
    },
    "WQ28": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.fields.hdrInput, 2000)
            .setValue(selectors.fields.hdrInput, data.WQ28.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ28.mke)
            .setValue(selectors.fields.oriInput, data.WQ28.ori)
            .setValue(selectors.fields.namInput, data.WQ28.nam)
            .click(selectors.dropDownBoxes.sexField.male)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ28.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ28.wgt)
            .setValue(selectors.fields.haiInput, data.WQ28.hai)
            .setValue(selectors.fields.offInput, data.WQ28.off)
            .setValue(selectors.fields.dowInput, data.WQ28.dow)
            .setValue(selectors.fields.olnInput, data.WQ28.oln)
            .setValue(selectors.fields.olsInput, data.WQ28.ols)
            .setValue(selectors.fields.oldInput, data.WQ28.old)
            .setValue(selectors.fields.licInput, data.WQ28.lic)
            .setValue(selectors.fields.lisInput, data.WQ28.lis)
            .setValue(selectors.fields.lidInput, data.WQ28.lid)
            .click(selectors.buttons.saveBtn).click(selectors.buttons.clearBtn)
        browser.expect.element(selectors.paragrahHeadings.queryTitle).text.to.contain('Submit query for validation.')
    },
    "WQ210": browser => {
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.hdrInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ210.wid)
            .setValue(selectors.fields.hdrInput, data.WQ210.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ210.mke)
            .setValue(selectors.fields.oriInput, data.WQ210.ori)
            .setValue(selectors.fields.namInput, data.WQ210.nam)
            .click(selectors.dropDownBoxes.sexField.male)
            .click(selectors.dropDownBoxes.raceField.white)
            .setValue(selectors.fields.hgtInput, data.WQ210.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ210.wgt)
            .setValue(selectors.fields.haiInput, data.WQ210.hai)
            .setValue(selectors.fields.offInput, data.WQ210.off)
            .setValue(selectors.fields.dowInput, data.WQ210.dow)
            .setValue(selectors.fields.olnInput, data.WQ210.oln)
            .setValue(selectors.fields.olsInput, data.WQ210.ols)
            .setValue(selectors.fields.oldInput, data.WQ210.old)
            .setValue(selectors.fields.licInput, data.WQ210.lic)
            .setValue(selectors.fields.lisInput, data.WQ210.lis)
            .setValue(selectors.fields.lidInput, data.WQ210.lid)
            .click(selectors.buttons.saveBtn)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field can only include numeric characters.')
    },
    "WQ27Enter": browser => {//Enter Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.paragrahHeadings.hdrHeader, 2000)
            .setValue(selectors.fields.hdrInput, data.WQ27.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ27.mke)
            .setValue(selectors.fields.oriInput, data.WQ27.ori)
            .setValue(selectors.fields.namInput, data.WQ27.nam)
            .click(selectors.fields.sexInput + ' ' + selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.fields.racInput + ' ' + selectors.dropDownBoxes.raceField.unknown)
            .setValue(selectors.fields.hgtInput, data.WQ27.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ27.wgt)
            .setValue(selectors.fields.haiInput, data.WQ27.hai)
            .setValue(selectors.fields.offInput, data.WQ27.off)
            .setValue(selectors.fields.dowInput, data.WQ27.dow)
            .setValue(selectors.fields.olnInput, data.WQ27.oln)
            .setValue(selectors.fields.olsInput, data.WQ27.ols)
            .setValue(selectors.fields.oldInput, data.WQ27.old)
            .setValue(selectors.fields.licInput, data.WQ27.lic)
            .setValue(selectors.fields.lisInput, data.WQ27.lis)
            .setValue(selectors.fields.lidInput, data.WQ27.lid)
            .click(selectors.buttons.saveBtn)
            .expect.element(selectors.paragrahHeadings.queryBody).text.to.contain('123abc!@#.A#+.def456ghi.A1#.U.U.001.001.red.AB12#.1900-01-01.1.UT.1900-01-01.AB123.HI.1900-01-01')

    },
    "WQ27Modify": browser => {//Modify Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.modifyOption, 2000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.paragrahHeadings.widHeader, 2000)
            .setValue(selectors.fields.widInput, data.WQ27.wid)
            .setValue(selectors.fields.hdrInput, data.WQ27.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ27.mke)
            .setValue(selectors.fields.oriInput, data.WQ27.ori)
            .setValue(selectors.fields.namInput, data.WQ27.nam)
            .click(selectors.fields.sexInput + ' ' + selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.fields.racInput + ' ' + selectors.dropDownBoxes.raceField.unknown)
            .setValue(selectors.fields.hgtInput, data.WQ27.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ27.wgt)
            .setValue(selectors.fields.haiInput, data.WQ27.hai)
            .setValue(selectors.fields.offInput, data.WQ27.off)
            .setValue(selectors.fields.dowInput, data.WQ27.dow)
            .setValue(selectors.fields.olnInput, data.WQ27.oln)
            .setValue(selectors.fields.olsInput, data.WQ27.ols)
            .setValue(selectors.fields.oldInput, data.WQ27.old)
            .setValue(selectors.fields.licInput, data.WQ27.lic)
            .setValue(selectors.fields.lisInput, data.WQ27.lis)
            .setValue(selectors.fields.lidInput, data.WQ27.lid)
            .click(selectors.buttons.saveBtn)
            .expect.element(selectors.paragrahHeadings.queryBody).text.to.contain('1234567890.123abc!@#.A#+.def456ghi.A1#.U.U.001.001.red.AB12#.1900-01-01.1.UT.1900-01-01.AB123.HI.1900-01-01')
    },
    "WQ211Enter": browser => {//Enter Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.paragrahHeadings.hdrHeader, 2000)
            .setValue(selectors.fields.hdrInput, data.WQ211.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ211.mke)
            .setValue(selectors.fields.oriInput, data.WQ211.ori)
            .setValue(selectors.fields.namInput, data.WQ211.nam)
            .click(selectors.fields.sexInput + ' ' + selectors.dropDownBoxes.sexField.unknown)
            .click(selectors.fields.racInput + ' ' + selectors.dropDownBoxes.raceField.unknown)
            .setValue(selectors.fields.hgtInput, data.WQ211.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ211.wgt)
            .setValue(selectors.fields.haiInput, data.WQ211.hai)
            .setValue(selectors.fields.offInput, data.WQ211.off)
            .setValue(selectors.fields.dowInput, data.WQ211.dow)
            .setValue(selectors.fields.olnInput, data.WQ211.oln)
            .setValue(selectors.fields.olsInput, data.WQ211.ols)
            .setValue(selectors.fields.oldInput, data.WQ211.old)
            .setValue(selectors.fields.licInput, data.WQ211.lic)
            .setValue(selectors.fields.lisInput, data.WQ211.lis)
            .setValue(selectors.fields.lidInput, data.WQ211.lid)
            .click(selectors.buttons.saveBtn)
            .expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Header" field should be between 9 and 19 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "MKE" field should be between 2 and 4 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Originating Agency Identifier" field should be 9 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Name" field should be between 3 and 30 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Height" field should be 3 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Weight" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Hair" field should be between 3 and 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Offense" field should be between 5 and 15 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain(`The "Date of Warrant/Violation" field must be entered as a date, MM/DD/YYYY, no earlier than 01/01/1900 and no later than today's date.`)
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "DL State" field should be 2 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "DL Expiration Date" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "License Plate" field should be between 5 and 8 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "License State" field should be 2 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "License Expiration Date" field can only include numeric characters.')

    },
    "WQ211Modify": browser => { //Modify Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.modifyOption, 2000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.widInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ211.wid)
            .setValue(selectors.fields.hdrInput, data.WQ211.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ211.mke)
            .setValue(selectors.fields.oriInput, data.WQ211.ori)
            .setValue(selectors.fields.namInput, data.WQ211.nam)
            .setValue(selectors.fields.hgtInput, data.WQ211.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ211.wgt)
            .setValue(selectors.fields.haiInput, data.WQ211.hai)
            .setValue(selectors.fields.offInput, data.WQ211.off)
            .setValue(selectors.fields.dowInput, data.WQ211.dow)
            .setValue(selectors.fields.olnInput, data.WQ211.oln)
            .setValue(selectors.fields.olsInput, data.WQ211.ols)
            .setValue(selectors.fields.oldInput, data.WQ211.old)
            .setValue(selectors.fields.licInput, data.WQ211.lic)
            .setValue(selectors.fields.lisInput, data.WQ211.lis)
            .setValue(selectors.fields.lidInput, data.WQ211.lid)
            .click(selectors.buttons.saveBtn)
            .expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Warrant ID" field should be 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Header" field should be between 9 and 19 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "MKE" field should be between 2 and 4 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Originating Agency Identifier" field should be 9 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Name" field should be between 3 and 30 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Height" field should be 3 characters long.')
        // browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Weight" field must be included.') Bug WQ2-33
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Hair" field should be between 3 and 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Offense" field should be between 5 and 15 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain(`The "Date of Warrant/Violation" field must be entered as a date, MM/DD/YYYY, no earlier than 01/01/1900 and no later than today's date.`)
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "DL State" field should be 2 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "DL Expiration Date" field can only include numeric characters.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "License Plate" field should be between 5 and 8 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "License State" field should be 2 characters long.')
        browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "License Expiration Date" field can only include numeric characters.')

    },
    "WQ229Enter": browser => { //Enter Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.enterOption, 2000)
            .click(selectors.buttons.enterOption)
            .waitForElementVisible(selectors.paragrahHeadings.hdrHeader, 2000)
            .setValue(selectors.fields.hdrInput, data.WQ229.hdr)
            .setValue(selectors.fields.mkeInput, data.WQ229.mke)
            .setValue(selectors.fields.oriInput, data.WQ229.ori)
            .setValue(selectors.fields.namInput, data.WQ229.nam)
            .setValue(selectors.fields.hgtInput, data.WQ229.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ229.wgt)
            .setValue(selectors.fields.haiInput, data.WQ229.hai)
            .setValue(selectors.fields.offInput, data.WQ229.off)
            .setValue(selectors.fields.dowInput, data.WQ229.dow)
            .setValue(selectors.fields.olnInput, data.WQ229.oln)
            .setValue(selectors.fields.olsInput, data.WQ229.ols)
            .setValue(selectors.fields.oldInput, data.WQ229.old)
            .click(selectors.buttons.saveBtn)
            .pause(100)
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Header" field should be between 9 and 19 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "MKE" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Originating Agency Identifier" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Name" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Sex" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Race / Ethnicity" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Height" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Weight" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Hair" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Offense" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain(`The "Date of Warrant/Violation" field must be included.`)
    },
    "WQ229Modify": browser => { //Modify Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.modifyOption, 2000)
            .click(selectors.buttons.modifyOption)
            .waitForElementVisible(selectors.fields.widInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ229.wid)
            .setValue(selectors.fields.hdrInput, data.WQ229.hdr2)
            .setValue(selectors.fields.mkeInput, data.WQ229.mke)
            .setValue(selectors.fields.oriInput, data.WQ229.ori)
            .setValue(selectors.fields.namInput, data.WQ229.nam)
            .setValue(selectors.fields.hgtInput, data.WQ229.hgt)
            .setValue(selectors.fields.wgtInput, data.WQ229.wgt)
            .setValue(selectors.fields.haiInput, data.WQ229.hai)
            .setValue(selectors.fields.offInput, data.WQ229.off)
            .setValue(selectors.fields.dowInput, data.WQ229.dow)
            .setValue(selectors.fields.olnInput, data.WQ229.oln)
            .setValue(selectors.fields.olsInput, data.WQ229.ols)
            .setValue(selectors.fields.oldInput, data.WQ229.old)
            .click(selectors.buttons.saveBtn)
            .expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field should be 10 characters long.')
    },
    // BUG WQ2-68
    // "WQ2191" : browser => { Minimum Cancel Wanted
    //     browser
    //     .click(selectors.buttons.menuIcon)
    //     .waitForElementVisible(selectors.buttons.cancelOption, 2000)
    //     .click(selectors.buttons.cancelOption)
    //     .waitForElementVisible(selectors.fields.widInput, 2000)
    //     .setValue(selectors.fields.widInput, data.WQ2191.wid)
    //     .setValue(selectors.fields.resInput, data.WQ2191.res)
    //     .setValue(selectors.fields.datInput, data.WQ2191.dat)
    //     .click(selectors.buttons.saveBtn)
    //     .expect.element()
    //},
    "WQ2192": browser => {   //<minimum Cancel Wanted
        browser
            .click(selectors.buttons.menuIcon)
            .waitForElementVisible(selectors.buttons.cancelOption, 2000)
            .click(selectors.buttons.cancelOption)
            .waitForElementVisible(selectors.fields.widInput, 2000)
            .setValue(selectors.fields.widInput, data.WQ2192.wid)
            .setValue(selectors.fields.resInput, data.WQ2192.res)
            .setValue(selectors.fields.datInput, data.WQ2192.dat)
            .click(selectors.buttons.saveBtn)
            .expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Warrant ID" field should be 10 characters long.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Reason for Cancellation" field must be included.')
        browser.expect.element(selectors.paragrahHeadings.errorList).text.to.contain('The "Date of Cancellation" field must be included.')


    },
    // Can't figure out why the test won't click the button -AJ advised to comment test out
    // "WQ2193": browser => {   //Cancel Wanted Empty Fields
    //     browser
    //         .click(selectors.buttons.menuIcon)
    //         .waitForElementVisible(selectors.buttons.cancelOption, 2000)
    //         .click(selectors.buttons.cancelOption)
    //         .waitForElementVisible(selectors.fields.widInput, 2000)
    //         .setValue(selectors.fields.widInput, data.WQ2193.wid)
    //         // .setValue(selectors.fields.resInput, data.WQ2193.res)
    //         .click(selectors.buttons.saveBtn)
    //         .pause(100000)
    //         .expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Warrant ID" field should be 10 characters long.')
    //     browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Reason for Cancellation" field must be included.')
    //     browser.expect.element(selectors.paragrahHeadings.results).text.to.contain('The "Date of Cancellation" field must be included.')
    // }

}