module.exports = {
    goodData: {
        input: {
            WQ26: {
                WID: '1234567890',
                hdr: 'ASDFeiw$. s',
                mke: 'Ad#',
                oai: '12345Sfer',
                nam: 'Joseph Hansen',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: '505',
                wgt: '130',
                hai: 'brown',
                off: 'ADdo3$ms. ',
                dow: '02022002',
                oln: '34DS34s#.',
                ols: 'CA',
                oly: '02182019',
                lic: '34Dsdo3',
                lis: 'Ut',
                liy: '12122020'
            },
            WQ23: {
                WID: '1234567890',
                hdr: 'ASDFeiw$. s',
                mke: 'Ad#',
                oai: '12345Sfer',
                nam: 'Joseph Hansen',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: '505',
                wgt: '130',
                hai: 'brown',
                off: 'ADdo3$ms. ',
                dow: '02022020',
                oln: '',
                ols: '',
                oly: '',
                lic: '',
                lis: '',
                liy: ''
            },
            WQ216: {
                WID: '1234445692',
                RFC: 'I felt like it',
                DOC: '12122019'
            }   
        }
    },
    badData: {
        input: {
            WQ28: {
                WID: 'JHsld45692',
                hdr: '           ',
                mke: '123',
                oai: 'sl..fs.!9',
                nam: '       ',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: 'fif',
                wgt: 'one',
                hai: '12345',
                off: '.........  ',
                dow: '',
                oln: '',
                ols: '',
                oly: '',
                lic: '',
                lis: '',
                liy: ''
            },
            WQ210: {
                WID: 'JHsld45692',
                hdr: 'sdlkds1232sw',
                mke: '123',
                oai: 'sl..fs.!9',
                nam: 'Mark Twain',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: '504',
                wgt: '110',
                hai: '12345',
                off: '12wsedrftg',
                dow: '',
                oln: '',
                ols: '',
                oly: '',
                lic: '',
                lis: '',
                liy: ''
            },
            WQ217: {
                WID: 'JHsld45692',
                RFC: '.........     ',
                DOC: '01010001'
            }      
        }
    }
}