module.exports = {
    
            WQ26: {
                WID: '1234567890',
                hdr: 'ASDFeiw$. s',
                mke: 'Ad#',
                oai: '12345Sfer',
                nam: 'Joseph Hansen',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: '505',
                wgt: '130',
                hai: 'brown',
                off: 'ADdo3$ms. ',
                dow: '02022002',
                oln: '34DS34s#.',
                ols: 'CA',
                oly: '02182019',
                lic: '34Dsdo3',
                lis: 'Ut',
                liy: '12122020'
            },
            WQ23: {
                WID: '1234567890',
                hdr: 'ASDFeiw$. s',
                mke: 'Ad#',
                oai: '12345Sfer',
                nam: 'Joseph Hansen',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: '505',
                wgt: '130',
                hai: 'brown',
                off: 'ADdo3$ms. ',
                dow: '02022020',
                oln: '',
                ols: '',
                oly: '',
                lic: '',
                lis: '',
                liy: ''
            },
            WQ216: {
                WID: '1234445692',
                RFC: 'I felt like it',
                DOC: '12122019'
            },
            WQ29: {
                //Enter Wanted Max Characters
                hdr: "Johnson1234567890$#",
                mke: "Ab*&",
                oai: "J8765kI90",
                nam: "MRS Bingo Big Daddy $$$!!!!!!!",
                sex: "Unknown",
                rac: "American Indian / Alaskan Native",
                hgt: "190",
                wgt: "999",
                hai: "blackerish",
                off: "123456789Zsw@#$",
                dow: "02/07/2017",
                oln: "aBcdef!23$567896Hnj*",
                ols: "TX",
                old: "01/31/2002",
                lic: "12345Hui",
                lis: "HI",
                lid: "04/06/1941",
                assembledQuery: "Johnson1234567890$#.Ab*&.J8765kI90.MRS Bingo Big Daddy $$$!!!!!!!.U.I.190.999.blackerish.123456789Zsw@#$.2017-02-07.aBcdef!23$567896Hnj*.TX.2002-01-31.12345Hui.HI.1941-04-06"
            },
            WQ253: {
                //Modify Wanted Max Characters
                wid: "1278569032",
                hdr: "^yh8i(kmtred$3234Ft",
                mke: "hu*!",
                oai: "456iOKuj0",
                nam: "My name is what I want it to b",
                sex: "Female",
                rac: "White",
                hgt: "098",
                wgt: "999",
                hai: "chocolatey",
                off: "ju6^89iesryy3!s",
                dow: "10/19/1981",
                oln: "JKio98765%7)(jnye#)t",
                ols: "CA",
                old: "04/16/2005",
                lic: "Mai7629j",
                lis: "MN",
                lid: "07/19/1978",
                assembledQuery: "1278569032.^yh8i(kmtred$3234Ft.hu*!.456iOKuj0.My name is what I want it to b.F.W.098.999.chocolatey.ju6^89iesryy3!s.1981-10-19.JKio98765%7)(jnye#)t.CA.2005-04-16.Mai7629j.MN.1978-07-19"
            },
            //Will not pass at this time due to bug WQ2-68
            // WQ259: {
            //     //Cancel Wanted Max Characters
            //     wid: "8903456217",
            //     res: "Im cancelling this because I want to and I do what I want Its just the way I am plus the convict game me a some mon$y and promised me a tower of gold!",
            //     date: "09/15/2007",
            //     assembledQuery: "8903456217.Im cancelling this because I want to and I do what I want Its just the way I am plus the convict game me a some mon$y and promised me a tower of gold!.2007/09/15"
            // }
            // },
            WQ227: {
                //Enter Wanted > max valid                
                hdr: "Johnson1234567890$#R",
                mke: "Ab*&x",
                oai: "J8765kI90t",
                nam: "BIG Bingo Big Daddy $$$!!!!!!!K",
                sex: "Unknown",
                rac: "American Indian / Alaskan Native",
                hgt: "1900",
                wgt: "9999",
                hai: "blackerishy",
                off: "123456789Zsw@#$t",
                dow: "02/07/2017",
                oln: "aBcdef!23$567896Hnj*m",
                ols: "TXS",
                old: "01/31/2005",
                lic: "12345Huim",
                lis: "HII",
                lid: "04/06/1941",


            },
            WQ250: {
                // Modify Wanted > max valid
                wid: "12345678902",
                hdr: "Johnson1234567890$#R",
                mke: "Ab*&x",
                oai: "J8765kI90t",
                nam: "&() Bingo Big Daddy $$$!!!!!!!K",
                sex: "Unknown",
                rac: "American Indian / Alaskan Native",
                hgt: "1900",
                wgt: "9999",
                hai: "blackerishy",
                off: "123456789Zsw@#$t",
                dow: "02/07/1918",
                oln: "aBcdef!23$567896Hnj*m",
                ols: "TXS",
                old: "01/31/1923",
                lic: "12345Huim",
                lis: "HII",
                lid: "04/06/1941",
            },
            WQ260: {
                //Cancel Wanted > max valid
                wid: "90672843679",
                res: "Im cancelling this because I want to and I do what I want Its just the way I am plus the convict game me a some mon$$y and promised me a tower of gold!",
                date: "09/20/1929",
            },
            WQ234: {
                //Enter Wanted max invalid
                hdr: "Johnson1234567890$",
                mke: "1234",
                oai: "&%$(*%)#$",
                nam: "MRS Bingo Big Daddy $$$!!!!!!!",
                sex: "Unknown",
                rac: "American Indian / Alaskan Native",
                hgt: "H*r",
                wgt: "wt(",
                hai: "123456&*()",
                off: "123456789Zsw@#",
                dow: "02/07/2001",
                oln: "aBcdef!23$567896Hnj*",
                ols: "23",
                old: "01/31/2000",
                lic: "!@#$%^&*",
                lis: "&^",
                lid: "04/06/1900",
            },
            WQ257: {
                //Modify Wanted invalid max characters
                wid: "UYLiy%&*Wd",
                hdr: "yiui908754^&3w#frui",
                mke: "1234",
                oai: "!@#$%^&*(",
                nam: "people have names others dont",
                sex: "male",
                rac: "Black",
                hgt: "REg",
                wgt: "tal",
                hai: "12345^&*()",
                off: "Doing bad Stuff",
                dow: "10/15/2012",
                oln: "!@#$%^&*()(*&^%$#@!#",
                ols: "RX",
                old: "10/12/1917",
                lic: "(*&!@%()",
                lis: "16",
                lid: "07/18/1974",
            },

            WQ261: {
                //Cancel Wanted invalid max characters
                wid: "*&uijyrw#$",
                res: "Sometimes people ch@nge their minds and that*s ok They always say th@# whatever you decide is going to be ok Whos they you ask The people I said that!",
                date: "10/17/1976"

            },



            WQ28: {
                WID: 'JHsld45692',
                hdr: '           ',
                mke: '123',
                oai: 'sl..fs.!9',
                nam: '       ',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: 'fif',
                wgt: 'one',
                hai: '12345',
                off: '.........  ',
                dow: '',
                oln: '',
                ols: '',
                oly: '',
                lic: '',
                lis: '',
                liy: ''
            },
            WQ210: {
                WID: 'JHsld45692',
                hdr: 'sdlkds1232sw',
                mke: '123',
                oai: 'sl..fs.!9',
                nam: 'Mark Twain',
                sexFemale: 'Female',
                sexMale: 'Male',
                sexUnknown: 'Unknown',
                sexOther: 'Other',
                sex: '',
                race: '',
                raceAsian: 'Asian / Pacific Islander',
                raceBlack: 'Black',
                raceHispanic: 'Hispanic',
                raceIndian: 'American Indian / Alaskan Indian',
                raceWhite: 'White',
                raceUnknown: 'Unknown',
                hgt: '504',
                wgt: '110',
                hai: '12345',
                off: '12wsedrftg',
                dow: '',
                oln: '',
                ols: '',
                oly: '',
                lic: '',
                lis: '',
                liy: ''
            },
            WQ217: {
                WID: 'JHsld45692',
                RFC: '.........     ',
                DOC: '01010001'
            },
      
    //Enter Wanted
    WQ27: {
        hdr: '123abc!@#',
        mke: 'A#+',
        ori: 'def456ghi',
        nam: 'A1#',
        sex: 'unknown',
        rac: 'unknown',
        hgt: '000',
        wgt: '0',
        hai: 'red',
        off: 'AB12#',
        dow: '01/01/1900',
        oln: '1',
        ols: 'UT',
        old: '01/01/1900',
        lic: 'AB123',
        lis: 'HI',
        lid: '01/01/1900'
    },
    //Modify Wanted (same Test Case-just added 0 at the end so we can distinguish the difference)
    WQ270: {
        wid: '1234567890',
        hdr: '123abc!@#',
        mke: 'A#+',
        ori: 'def456ghi',
        nam: 'A1#',
        sex: 'unknown',
        rac: 'unknown',
        hgt: '000',
        wgt: '0',
        hai: 'red',
        off: 'AB12#',
        dow: '01/01/1900',
        oln: '1',
        ols: 'UT',
        old: '01/01/1900',
        lic: 'AB123',
        lis: 'HI',
        lid: '01/01/1900'
    },
    //Enter Wanted
    WQ211: {
        hdr: 'Header',
        mke: '#',
        ori: 'def456gh',
        nam: 'A1',
        sex: '',
        rac: '',
        hgt: '00',
        wgt: '',
        hai: 're',
        off: 'AB12',
        dow: '01/01/1899',
        oln: '',
        ols: 'A',
        old: '',
        lic: 'AB12',
        lis: 'H',
        lid: '01/01/1899'
    },
    //Modify Wanted 
    WQ2110: {
        wid: '123',
        hdr: 'Header',
        mke: '#',
        ori: 'def456gh',
        nam: 'A1',
        sex: '',
        rac: '',
        hgt: '00',
        wgt: '',
        hai: 're',
        off: 'AB12',
        dow: '01/01/1899',
        oln: '',
        ols: 'A',
        old: '',
        lic: 'AB12',
        lis: 'H',
        lid: '01/01/1899'
    },
    //Enter Wanted
    WQ229: {
        hdr: '',
        mke: '',
        ori: '',
        nam: '',
        sex: '',
        rac: '',
        hgt: '',
        wgt: '',
        hai: '',
        off: '',
        dow: '',
        oln: '',
        ols: '',
        old: '',
        lic: '',
        lis: '',
        lid: ''
    },
    //Modify wanted (WID can't be empty or submit button is disabled.)
    WQ2290: {
        wid: '123',
        hdr: '',
        mke: '',
        ori: '',
        nam: '',
        sex: '',
        rac: '',
        hgt: '',
        wgt: '',
        hai: '',
        off: '',
        dow: '',
        oln: '',
        ols: '',
        old: '',
        lic: '',
        lis: '',
        lid: ''
    },
    //Cancel Wanted Min
    WQ2192: {
        wid: '1234567890',
        res: 'because 123',
        dat: '01/01/1900'
    },
    //Cancel Wanted <Min
    WQ2192: {
        wid: '123456789',
        res: 'because',
        dat: '01/01/1899'
    },
    //Cancel Wanted Empty Fields
    WQ2192: {
        wid: '123',
        res: '',
        dat: ''
    },


}

